
package com.jetherrodrigues.jaxws.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.unisal.interfaces.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculable", targetNamespace = "http://interfaces.unisal.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculable {


    /**
     * 
     * @param divisor
     * @param dividend
     * @return
     *     returns double
     * @throws SOAPException
     */
    @WebMethod(action = "http://localhost:8080/calculator/divide")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://interfaces.unisal.br/", className = "br.unisal.interfaces.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://interfaces.unisal.br/", className = "br.unisal.interfaces.DivisionResponse")
    @Action(input = "http://localhost:8080/calculator/divide", output = "http://interfaces.unisal.br/Calculable/divisionResponse", fault = {
        @FaultAction(className = SOAPException.class, value = "http://interfaces.unisal.br/Calculable/division/Fault/SOAPException")
    })
    public double division(
        @WebParam(name = "dividend", targetNamespace = "")
        double dividend,
        @WebParam(name = "divisor", targetNamespace = "")
        double divisor)
        throws SOAPException
    ;

}
